import './globals.css';
import { Providers } from '../components/providers'
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';

import Header from 'src/components/header';
import HeaderMobile from 'src/components/header-mobile';
import MarginWidthWrapper from 'src/components/margin-width-wrapper';
import PageWrapper from 'src/components/page-wrapper';


const montserrat = Montserrat ({  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], style: "normal", subsets: ["latin"] });  

export const metadata: Metadata = {
  title: 'Dona 3D - Impresion 3D',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`bg-white dark:bg-[#050505] ${montserrat.className}`}>
        <Providers>
          <div className="flex">
            <main className="flex-1">
              <Header />
              <MarginWidthWrapper>
                <HeaderMobile />
                <PageWrapper>{children}</PageWrapper>
              </MarginWidthWrapper>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
